fix(fetchers): Fix provider override
morpho-org/morpho-aave-v3-sdk pull request #54
Opened 2023-07-05 14:18 UTC by oumar-fall

### Description of change

### Pull-Request Checklist

- [ ] Code is up-to-date with the `main` branch
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

2023-07-05 14:38 UTC, julien-devatom requested changes
init is not called when setting the provider https://github.com/morpho-org/morpho-aave-v3-sdk/blob/fix/provider-override/src/fetchers/Chain/ChainFetcher.ts#L23C16-L23C27

2023-07-05 14:40 UTC, oumar-fall commented
> init is not called when setting the provider https://github.com/morpho-org/morpho-aave-v3-sdk/blob/fix/provider-override/src/fetchers/Chain/ChainFetcher.ts#L23C16-L23C27

Yes but it is called at every fetch (maybe we should change this)

2023-07-05 15:19 UTC, julien-devatom commented
But if [poolDataProvider](https://github.com/morpho-org/morpho-aave-v3-sdk/blob/fix/provider-override/src/fetchers/Chain/ChainMarketFetcher.ts#L42) is set, there is no reinitialization. So we have to force reinit when we change the provider

2023-07-06 07:15 UTC, julien-devatom approved these changes

2023-07-06 07:15 UTC, merged